[package]
name = "syntaxia"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
poise = "0.6.1"
regex = "1.10.6"
serde = "1.0.209"
serde_yaml = "0.9.34"
serenity = "0.12"
thiserror = "1.0.63"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
